title: InnovaCoreTech Blog Example
subtitle: Blogs about stuff! 
description: >- # this means to ignore newlines until the next key
  Blogs about stuff! 

url: "https://ict.rbleattler.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
